<?php

// Implements hook_help
function loginmenu_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/modules#description':
      $output .= t('Generates a login link for anonymous users');
      break;
    case 'admin/help#loginmenu':
      $output .= '<p>'. t('By design the login link will be at the top of the menu.'). '</p>';
      break;
    case 'admin/help/loginmenu':
      $output .= t('Generates a login link in the navigation menu for anon only.');
      break;
  }
  return $output;
}

// Implements hook_menu
function loginmenu_menu() {
  $items = array();
  $items['login'] = array(
    'title'           => t('Log in'),
    'description'     => t('Log in'),
    'access callback' => 'loginmenu_access',
    'access arguments' => array('access login'),
    'page callback'   => 'loginmenu_redirect',
    'type'            => MENU_NORMAL_ITEM,
    'weight'          => 10,
  ); 
  return $items;
}

// handles menu item access
function loginmenu_access() {
  return (!($GLOBALS['user']->uid));
}

// handles menu item callback
function loginmenu_redirect() {
  drupal_goto('user');
}

function loginmenu_permission() {
    return array(
        'access login' => array(
            'title' => t('Access the login menu'),
            'description' => t('Access permissions for login menu'),
        ),
    );
}

